# tasks.py
from invoke import task

COMPOSE_FILE = "docker-compose.yml"
ENV_FILE = ".env"
SERVICE = "api"

COMPOSE = f"docker compose -f {COMPOSE_FILE} --env-file {ENV_FILE}"


@task
def help(c):
    print("Available commands:")
    print("  uv run invoke docker-build        # build and start the image")
    print("  uv run invoke docker-up           # start in the background")
    print("  uv run invoke docker-down         # stop the services")
    print("  uv run invoke docker-down-v       # stop and remove volumes")
    print("  uv run invoke logs                # stream API logs")
    print("  uv run invoke ps                  # show container status")
    print("  uv run invoke db-revision -m MSG  # create an Alembic migration")
    print("  uv run invoke db-up               # apply migrations")
    print("  uv run invoke db-down             # roll back one migration")
    print("  uv run invoke db-history          # show migration history")
    print("  uv run invoke db-current          # show the current revision")
    print("  uv run invoke tests               # run pytest")


# ===== Docker =====
@task
def docker_build(c):
    """Build the image and run it in the foreground."""
    c.run(f"{COMPOSE} up --build")

@task
def docker_up(c):
    """Start the containers in the background."""
    c.run(f"{COMPOSE} up -d")

@task
def docker_down(c):
    """Stop the containers."""
    c.run(f"{COMPOSE} down")

@task
def docker_down_v(c):
    """Stop the containers and remove their volumes."""
    c.run(f"{COMPOSE} down -v")

@task
def logs(c):
    """Stream logs from the API service."""
    c.run(f"{COMPOSE} logs -f {SERVICE}")

@task
def ps(c):
    """Show container status."""
    c.run(f"{COMPOSE} ps")


# ===== Alembic =====
@task(help={"m": "migration message, e.g. 'init schema'"})
def db_revision(c, m="new migration"):
    """Create a new autogenerated migration."""
    c.run(
        f'{COMPOSE} exec {SERVICE} uv run alembic revision --autogenerate -m "{m}"'
    )

@task
def db_up(c):
    """Apply all migrations."""
    c.run(f"{COMPOSE} exec {SERVICE} uv run alembic upgrade head")

@task
def db_down(c):
    """Roll back one migration."""
    c.run(f"{COMPOSE} exec {SERVICE} uv run alembic downgrade -1")

@task
def db_history(c):
    """Show migration history."""
    c.run(f"{COMPOSE} exec {SERVICE} uv run alembic history --verbose")

@task
def db_current(c):
    """Show the current migration revision."""
    c.run(f"{COMPOSE} exec {SERVICE} uv run alembic current")


# ===== Tests =====
@task
def tests(c):
    """Run pytest inside the API container."""
    c.run(f"{COMPOSE} exec {SERVICE} uv run pytest")
